### ISSUE TITLE
Can we submit Flatpak to Flathub?

### ISSUE THREAD

**Issue by kevinsmia1939** [qelectrotech/qelectrotech-source-mirror#143]
Hi,

I noticed that we have working flatpak manifest file.
https://github.com/qelectrotech/qelectrotech-source-mirror/tree/master/build-aux/flatpak

But I don't see qelectrotech in Flathub. Can we upload it there?
https://flathub.org/home

**Comment by scorpio810** [comment]
Hi,
yes you can, thanks in advance.

**Comment by kevinsmia1939** [comment]
> Hi,
> yes you can, thanks in advance.
> 
> https://qelectrotech.org/forum/viewtopic.php?id=1582

Hi,

I just create the pull request, if they like the package they will ask you to become the maintainer.
https://github.com/flathub/flathub/pull/2146

**Comment by ppd** [comment]
This has been  live for some time at https://flathub.org/apps/details/org.qelectrotech.QElectroTech. Closing.
