### ISSUE TITLE
Refreshing after making changes to elements

### ISSUE THREAD

**Issue by freemovers** [qelectrotech/qelectrotech-source-mirror#168]
After making changes to the elements (for example adding or changing the text) the element will not update on the folio. Also, new elements that are added to the collections do not show up. A restart of QElectroTech is required to see these changes to the elements.

**Comment by scorpio810** [comment]
What version?
Also right click on collection -> reload collection.

**Comment by freemovers** [comment]
I am running V 0.80c+87c957a06d79751d3
Reload collections seems to fix the second issue of adding elements, and now it even shows the new elements without reloading already as well. I noticed a reload function in the element editor as well, and it seems from old videos that there used to be a reload function on the folio as well. 
BTW, great job on this application! Very user-friendly and looks like after I setup a User Collection it will be fast to create new schematics.
