### ISSUE TITLE
snap: Update stable release to core20 & introduce branch for stable releases

### ISSUE THREAD

**Issue by ppd** [qelectrotech/qelectrotech-source-mirror#201]
Now that https://github.com/snapcore/snapcraft/pull/3596 has landed, we should do the following things:

- ~[ ] Branch off 0.8 to be able to update the snap packaging for the stable release~
- [x] Port the stable release to core20. Master has the recipe already.
- [x] Change the user visible version in the store to 0.8 without the git suffix
- [x] Introduce a workflow for rebuilding the stable track if security updates require it

**Comment by ppd** [comment]
@scorpio810 Maybe the cleanest way to manage the snaps would be to have a separate snap repo "qelectrotech-snap". There we would copy the packaging for the stable release. The build files for edge stay in the main repo.

**Comment by ppd** [comment]
snapcore/snapcraft#3596 has been released to stable in https://github.com/snapcore/snapcraft/releases/tag/6.0.1

I'll port the stable release soon.

**Comment by scorpio810** [comment]
Great, thanks.

**Comment by ppd** [comment]
I'm putting the recipes & workflows for stable snaps here: https://github.com/qelectrotech/qelectrotech-snap

**Comment by ppd** [comment]
@scorpio810 Can you maybe try 0.8.0 from the candidate channel? `snap refresh --candidate qelectrotech`. It's 0.8.0 built with the current recipe from master, including core20, newer Qt, updated dependencies etc.
For me, it looks good. I'll promote it to stable if I get one or two positive feedbacks.

**Comment by ppd** [comment]
A branch for publishing stable release updates (first to candidate, then we release them to stable by hand): https://github.com/qelectrotech/qelectrotech-source-mirror/tree/snap/latest/candidate

The workflow run for a 0.8.0 rebuild on core20: https://github.com/qelectrotech/qelectrotech-source-mirror/actions/runs/1722623821

**Comment by ppd** [comment]
Released revision 1452 to stable.
