### ISSUE TITLE
File dialog should enforce suffix

### ISSUE THREAD

**Issue by ppd** [qelectrotech/qelectrotech-source-mirror#206]
@scorpio810 This commit 
https://github.com/qelectrotech/qelectrotech-source-mirror/commit/b121dad5625512658b1511059e264161affa6341
disables appending the correct suffix. 

People have a hard time finding those files again because they get saved without the .qet suffix. 

For some reason, the QFileDialog::getSaveFileName() does not display a default name when using the xdg-desktop-portal backend. Could be a Qt bug.

**Comment by scorpio810** [comment]
Flatpak need to keep this patch.

**Comment by ppd** [comment]
This has been fixed on master in 688d9fe.

**Comment by ppd** [comment]
Released to stable in revision 1452.
