### ISSUE TITLE
Polylines always closed on dxf export

### ISSUE THREAD

**Issue by FabianInostroza** [qelectrotech/qelectrotech-source-mirror#228]
Draw any non closed polyline on a page and export it to dxf.
The polyline in the dxf output is always closed.

**Comment by scorpio810** [comment]
Maybe contact C-born
see:

https://github.com/qelectrotech/qelectrotech-source-mirror/pulls?q=is%3Apr+is%3Aclosed+DXF

**Comment by scorpio810** [comment]
Hello C-born
please see this issue:
https://github.com/qelectrotech/qelectrotech-source-mirror/issues/228

**Comment by c-born** [comment]
Qet uses a Qt polygon to store both polygons (closed objects by definition) and polylines, and the "Draw Polygon" function actually allows you to draw polylines as well as polygons.
In the old DXF format we are currently using both are saved as polylines anyway, this may change when I get around to updating DXF format to a more recent and capable version.
For now I've modified the code to use the "DrawPolygon" or "DrawPolyline" output functions based on whether the polgon is flagged as closed or open. This should fix the reported problem, please test and let me know if there are any concerns.
Changes are pushed to the tuxfamily master repo, so should appear here at the next sync.

**Comment by scorpio810** [comment]
Thanks David,

Best regards,
Laurent
