### ISSUE TITLE
Question about ARM target in future release

### ISSUE THREAD

**Issue by george-andrei** [qelectrotech/qelectrotech-source-mirror#238]
Hello,

I just discovered this awesome project, and first I would like to say a big thank you to the community around this project. Looks amazing! 😃 

As I am a user of Linux on ARM, I am wondering if there is any plan to compile the binaries for ARM, or if someone already experimented around this. If not, I am gladly open to test for you. 
In my opinion, ARM is getting more and more popular on desktop. First Apple with their M1s and now Microsoft is pushing it as well, so I see only benefits. 
To be honest, I don't know how much work the implementation of ARM target would mean for this project, so don't get me wrong, I am just curious if this has been already discussed or not. 

Cheers!

**Comment by scorpio810** [comment]
Like Debian for QET stable version, in my PPA you have ARM ports for the 0.9-dev
https://launchpad.net/~scorpio/+archive/ubuntu/qelectrotech-dev/+packages

Architecture tag: armhf: ARM ARMv7 Hard Float 
Architecture tag: arm64: ARM ARMv8

**Comment by george-andrei** [comment]
Hi @scorpio810,

Thanks a lot, that worked like a charm! 
Because use a PineBook Pro with Manjaro on it, I had to convert the .deb into a .pkg with `debtap`, but after this step, I installed the package with not problem:

![image](https://user-images.githubusercontent.com/12943454/208714765-ce98f9e8-73da-46f9-980e-cb8c8e1a7ee7.png)

With the holydays approaching, I will not have the time to further test this, but will surely do in 2023 😉 

(Note for the bots: I use Manjaro ARM with kernel 6.0.12 and QET V0.90-DEV)

**Comment by scorpio810** [comment]
Hi @george-andrei,

thanks for your feedback,
You could share QET logs?

**Comment by scorpio810** [comment]
![208714765-ce98f9e8-73da-46f9-980e-cb8c8e1a7ee7](https://user-images.githubusercontent.com/19955399/208990518-45a7bdaa-149b-44f2-88b1-e72b56dcd2fa.png)
Your version is very old, try latest builds

**Comment by scorpio810** [comment]
Hi @george-andrei,
I would like to buy the new mac mini M2 to make universal bundles for macOS (arch:amd64 & arm64):

https://qelectrotech.org/forum/viewtopic.php?id=2393

> Hello,
> 
> I just discovered this awesome project, and first I would like to say a big thank you to the community around this project. Looks amazing! smiley
> 
> As I am a user of Linux on ARM, I am wondering if there is any plan to compile the binaries for ARM, or if someone already experimented around this. If not, I am gladly open to test for you. In my opinion, ARM is getting more and more popular on desktop. First Apple with their M1s and now Microsoft is pushing it as well, so I see only benefits. To be honest, I don't know how much work the implementation of ARM target would mean for this project, so don't get me wrong, I am just curious if this has been already discussed or not.
> 
> Cheers!

Hi @george-andrei,
I would like to buy the new mac mini M2 to make universal bundles for macOS (arch:amd64 & arm64):

https://qelectrotech.org/forum/viewtopic.php?id=2393

**Comment by george-andrei** [comment]
Hi @scorpio810,

Sorry about the small delay but I was away for a while :-)
Here are the logs:

```
17:35:53.150 Info: Start-up 
17:35:53.154 Debug: "File /home/george/.qet/20221220.log is deleted!" (sources/main.cpp:150, void delete_old_log_files(int))
17:35:53.620 Info: Elements collection reload 
17:35:53.652 Info: Elements collection finished to be loaded in 0.03 seconds 
17:35:53.753 Info: debugging enabled: false 
17:35:53.754 Info: Qt library version: 5.15.7 
17:35:53.755 Info: Qt library location default prefix: "/usr" 
17:35:53.756 Info: Qt library location documentation: "/usr/share/doc/qt" 
17:35:53.756 Info: Qt library location headers: "/usr/include/qt" 
17:35:53.757 Info: Qt library location libraries: "/usr/lib" 
17:35:53.758 Info: Qt library location executables: "/usr/lib/qt/libexec" 
17:35:53.759 Info: Qt library location Qt binaries: "/usr/bin" 
17:35:53.759 Info: Qt library location Qt plugins: "/usr/lib/qt/plugins" 
17:35:53.760 Info: Qt library location installed QML extensions: "/usr/lib/qt/imports" 
17:35:53.761 Info: Qt library location installed QML extensions: "/usr/lib/qt/qml" 
17:35:53.761 Info: Qt library location dependent Qt data: "/usr/lib/qt" 
17:35:53.762 Info: Qt library location independent Qt data: "/usr/share/qt" 
17:35:53.763 Info: Qt library location translation: "/usr/share/qt/translations" 
17:35:53.764 Info: Qt library location examples: "/usr/share/doc/qt/examples" 
17:35:53.764 Info: Qt library location Qt testcases: "/usr/tests" 
17:35:53.765 Info: Qt library location Qt settings: "/etc/xdg" 
17:35:53.765 Info: "QElectroTech V 0.90-DEV+acd151c9cb0a58100c957a06d79751d3" 
17:35:53.766 Info: "Compilation : GCC 11.2.0" 
17:35:53.766 Info: "Built with Qt 5.15.2 - arm64 - Date : Jul 16 2022 : 11:48:05" 
17:35:53.766 Info: "Run with Qt 5.15.7 using 6 thread(s)" 
17:35:53.767 Info: "CPU : " 
17:35:53.767 Info: "RAM Total : 3 GB" 
17:35:53.767 Info: "RAM Available : 1 GB" 
17:35:53.767 Info: "GPU : " 
17:35:53.768 Info: "GPU RAM :     Video memory: 3868MB\n" 
17:35:53.768 Info: "OS : linux  - arm64 - Version : Manjaro ARM - Kernel : 6.0.12-1-MANJARO-ARM" 
17:35:53.768 Info: *** Qt screens *** 
17:35:53.769 Info: "( 1 : 1920 x 1080 )" 
17:35:53.779 Info: DISK : /run   
17:35:53.780 Info: FileSystemType: "tmpfs" 
17:35:53.780 Info: SizeTotal: 2 GB 
17:35:53.780 Info: AvailableSize: 2 GB 
17:35:53.780 Info: DISK : /   
17:35:53.781 Info: FileSystemType: "ext4" 
17:35:53.781 Info: SizeTotal: 61 GB 
17:35:53.781 Info: AvailableSize: 16 GB 
17:35:53.782 Info: DISK : /tmp   
17:35:53.782 Info: FileSystemType: "tmpfs" 
17:35:53.782 Info: SizeTotal: 2 GB 
17:35:53.783 Info: AvailableSize: 2 GB 
17:35:53.783 Info: DISK : /boot   
17:35:53.783 Info: FileSystemType: "vfat" 
17:35:53.784 Info: SizeTotal: 0 GB 
17:35:53.784 Info: AvailableSize: 0 GB 
17:35:53.784 Info: DISK : /run/user/1000   
17:35:53.785 Info: FileSystemType: "tmpfs" 
17:35:53.785 Info: SizeTotal: 0 GB 
17:35:53.785 Info: AvailableSize: 0 GB 
17:35:53.785 Info: DISK : /var/lib/docker/overlay2/8cb70b299f90d8cba3508df87ddbb2fa0910ed94243439e2c8b75403f0249597/merged   
17:35:53.786 Info: FileSystemType: "overlay" 
17:35:53.786 Info: SizeTotal: 0 GB 
17:35:53.786 Info: AvailableSize: 0 GB 
17:35:53.787 Info: DISK : /run/docker/netns/4d5aef12f301   
17:35:53.787 Info: FileSystemType: "nsfs" 
17:35:53.787 Info: SizeTotal: 0 GB 
17:35:53.787 Info: AvailableSize: 0 GB 
17:35:53.788 Info: DISK USED: /   
17:35:53.789 Info: FileSystemType: "ext4" 
17:35:53.789 Info: SizeTotal: 61 GB 
17:35:53.789 Info: AvailableSize: 16 GB 

```

**Comment by scorpio810** [comment]
FYI, Remi build now QET on arm64 ARCH RPM:
https://blog.remirepo.net/post/2023/09/15/New-2023-ARM-builder
