### ISSUE TITLE
right click on text crashes app

### ISSUE THREAD

**Issue by viktor-c** [qelectrotech/qelectrotech-source-mirror#260]
Been working on this software for about a week now. When trying to change font size of pasted text i selected the text box, then double click to enter into edit mode, then right click in the text box and the app crashes.
Tried with different text boxes....

segmentation fault (core dumped)  ./apps/QElectroTech_0.100.0-r7854-x86_64.AppImage

Thanks!

**Comment by ManfredHerrmann** [comment]
same problem ... as a workaround this works:
 "select text-box > crtl+e" or "right-mouse-button>edit"

**Comment by scorpio810** [comment]
Please retry latest build:
https://download.qelectrotech.org/qet/builds/AppImage/0.100.0/QElectroTech_0.100.0-r7868-x86_64.AppImage

**Comment by asilnevs** [comment]
I had the same problem and it seems that this latest build solved the problem for me.
Thanks for the fix.

**Comment by scorpio810** [comment]
Strange ....the file maybe must have been corrupted during the server transfer or when old hoster TuxFamlily down...[Main services down](https://www.tuxfamily.org/fr/news/2023070900)...

I just rebuild and upload new version again, thanks for feedback
