### ISSUE TITLE
https://qelectrotech.org/ is down for several days now !

### ISSUE THREAD

**Issue by MacGeyer** [qelectrotech/qelectrotech-source-mirror#261]
What's happening with the website ?

**Comment by scorpio810** [comment]
https://www.tuxfamily.org/fr/news

[Main services down](https://www.tuxfamily.org/fr/news/2023070900)
Posté le dimanche 9 juillet 2023, à 15:51 UTC

Today, around 11:37 UTC, we lost contact with some of our most important hosts, presumably following yet another power hiccup. Consequently, our main services (web areas, databases, SCM repositories, access to mailboxes, etc.) are down. Secondary services (MX2, NS2, etc.) are still up and running, along with download repositories. As this is being written, we cannot predict when exactly our services will recover and can only apologize for the significant downtime incurred. Please bear with us.

**Comment by scorpio810** [comment]
Seem's fixed, now.

**Comment by xavierog** [comment]
> Seem's fixed, now.

@scorpio810 please contact me through TuxFamily IRC.

**Comment by MacGeyer** [comment]
https://qelectrotech.org/ is still not responding !
Where can the latest version be downloaded  ?

**Comment by De-Backer** [comment]
Where can the latest version be downloaded ?
=>
https://download.tuxfamily.org/qet/builds/
And
https://qelectrotech.org/ is still not responding !
see:
https://www.tuxfamily.org/fr/main

**Comment by scorpio810** [comment]
> > Seem's fixed, now.
> 
> @scorpio810 please contact me through TuxFamily IRC.

@xavierog send me informations by email, please.

**Comment by scorpio810** [comment]
thanks 

> Where can the latest version be downloaded ? => https://download.tuxfamily.org/qet/builds/ And https://qelectrotech.org/ is still not responding ! see: https://www.tuxfamily.org/fr/main

thanks Simon. ;)

**Comment by scorpio810** [comment]
FYI, following the many problems encountered recently, we decided to leave our host friends whom I had been with for almost 20 years, and to migrate qelectrotech.org to another host which will be at our expense.. ~150€/year...

We hope to restore all the infrastructure in a few days if all goes well, please wait.
Sorry about that!

Regards,
Laurent

**Comment by scorpio810** [comment]
Web area is now out.
