### ISSUE TITLE
Error using Portuguese Language

### ISSUE THREAD

**Issue by dominus04** [qelectrotech/qelectrotech-source-mirror#274]
The problem is when you choose Brazilian Portuguese as language. There is a conflict between block title language and app language.
When you choose brazilian portuguese as app language, the block titles and sheets remain in french, but when you choose language as system language, the block title change to portuguese, but app change to french.
My system is configured as brazilian portuguese.

**Comment by scorpio810** [comment]
Maybe related to this https://github.com/qelectrotech/qelectrotech-source-mirror/issues/278

**Comment by scorpio810** [comment]
@dominus04  what version of QET, OS?

**Comment by plc-user** [comment]
An additional question:
Can QET handle language-encodings with more than two letters in titleblocks and/or elements?
When I want to add a language like "pt_BR" for an element in element-editor the line is NOT added in the file. It isn't even added in the list of the dialog-box in element-editor! (close and re-open dialog)
When I add a language like "pt_BR" to the list of languages in an element-file "by hand" and change the language of QET to Brazilian Portuguese the added name of the element is not shown: It is named in another language.

**Comment by scorpio810** [comment]
For me the problem comes from the fact that more than two characters are not possible in the titleblock code.

**Comment by plc-user** [comment]
The titleblock-code was the least place where I searched for language-settings...

**Comment by scorpio810** [comment]
Please try new 0.100.0-dev packages, thanks plc-user.

Use "pt_BR" for your translation to  Brazilian Portuguese.
