### ISSUE TITLE
Bad file name for  translations

### ISSUE THREAD

**Issue by remicollet** [qelectrotech/qelectrotech-source-mirror#278]
- `qet_zh-cn.qm` should be  `qet_zh_CN.qm`
- `qet_pt_br.qm` should be `qet_pt_BR.qm`

See content of /usr/share/qt5/translations/
```
...
/usr/share/qt5/translations/qtbase_pt_BR.qm
/usr/share/qt5/translations/qtbase_ru.qm
/usr/share/qt5/translations/qtbase_sk.qm
/usr/share/qt5/translations/qtbase_tr.qm
/usr/share/qt5/translations/qtbase_uk.qm
/usr/share/qt5/translations/qtbase_zh_CN.qm
/usr/share/qt5/translations/qtbase_zh_TW.qm
...
```

**Comment by plc-user** [comment]
I think this change can easily be done with an advanced text editor such as "Kate":

Replace all occurrences of "pt_br" with "pt_BR". As far as I can see, it only affects Brazilian Portuguese at the moment and there are only three files that need to be changed (plus element and title block files).

Of course, this also has to be done in the various (build) scripts that Laurent and Joshua use.

I have tried this on my local system and assume that this is also possible for the official QET version. But of course the developers should evaluate this! (I can create a pull-request, if wanted)

Nevertheless, the effect from is still present, which I described in  #274

**Comment by scorpio810** [comment]
I've made the changes, if I've forgotten anything please send a PR.

**Comment by plc-user** [comment]
Found one place in cmake-file and some titleblocks.
Should be fixed now in all files!

**Comment by scorpio810** [comment]
Please try new 0.100.0-dev packages, thanks plc-user.
