### ISSUE TITLE
README 404 Not Found URL: qelectrotech.org/download.html needs to be qelectrotech.org/download.php

### ISSUE THREAD

**Issue by marc-medley** [qelectrotech/qelectrotech-source-mirror#298]
README.md "… which can also be **downloaded**." [https://qelectrotech.org/download.html](https://qelectrotech.org/download.html) URL goes to a 404 Not Found page.

The downloads URL needs to be updated to [https://qelectrotech.org/download.php](https://qelectrotech.org/download.php) which works OK.

**Comment by scorpio810** [comment]
Fixed, thank you.
