### ISSUE TITLE
Cannot open qelectrotech.app on macOS Sequoia 15.0

### ISSUE THREAD

**Issue by MacValley** [qelectrotech/qelectrotech-source-mirror#307]
I downloaded qelectrotech-0.100.0-r8146-arm64.zip which contains the file qelectrotech.app.
When opening the file I get: “qelectrotech.app” is damaged and can’t be opened. You should move it to the Bin.
I have a MacBook Pro M2 with chip Apple M2 Pro, running the latest OS, macOS Sequoia 15.0.

Anyone experiencing the same problem?

**Comment by Spokplacenta** [comment]
Same error

**Comment by MacValley** [comment]
Today I downloaded qelectrotech-0.100.0-r8152-arm64.zip, and this was successfully opened. So whatever the difference
 is between r8152 and r8146, it now works. Great! I will close the issue that I opened last week.

**Comment by Spokplacenta** [comment]
I just tested the r8152 version, I still can't open it
![image](https://github.com/user-attachments/assets/cfd63792-15f8-45de-b63c-ad1fb9262feb)

**Comment by nightscape** [comment]
Same here on a MacBook Air M1 on MacOs Sequoia. It says
![image](https://github.com/user-attachments/assets/cbc7ceef-d745-469a-bcc6-c5e514636e35)
for both 8152 and 8166.

**Comment by gieljnssns** [comment]
I've tried with every version I can download on https://download.qelectrotech.org/qet/builds/MAC_OS_X/arm64/
Always the same error
<img width="274" alt="Scherm­afbeelding 2024-11-08 om 11 13 36" src="https://github.com/user-attachments/assets/9847daa5-255c-41e2-8e84-5bcc884b97af">

**Comment by gieljnssns** [comment]
If you do this, you can get it working
![Scherm­afbeelding 2024-11-08 om 11 29 16](https://github.com/user-attachments/assets/be480ead-7dfa-46f6-9566-26d9369a2ce4)
