### ISSUE TITLE
missing group functionality

### ISSUE THREAD

**Issue by RomainBTSea** [qelectrotech/qelectrotech-source-mirror#318]
Hi, I can't see any option to group elements. My goal is to rotate multiple parts of elements in the element editor 
![image](https://github.com/user-attachments/assets/db7dfbfb-6fb1-46de-bc99-1a23a582c9e6)
![image](https://github.com/user-attachments/assets/108769f7-4e68-4e25-8286-d114aacb098b)

attached an image when trying to rotate the whole thing

Thanks

**Comment by scorpio810** [comment]
Hi see:
https://download.qelectrotech.org/qet/QET_ElementScaler_quick-guide/

https://qelectrotech.org/forum/viewtopic.php?pid=14368#p14368

**Comment by scorpio810** [comment]
Btw QET_ElementScaler binary work aonly in gui on 0.100-dev QET version.

**Comment by RomainBTSea** [comment]
thank you for the quick reply, just tested it, works well and useful.
Is there a way to rotate 90° the element ?

**Comment by scorpio810** [comment]
Maybe see 

https://github.com/plc-user/QET_ElementScaler

**Comment by RomainBTSea** [comment]
Great! Thank you
